config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "articles#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # config/routes.rb
  resources :articles, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :comments, only: [:create, :edit, :show, :destroy]
    member do
      get 'show_article' # Agrega esta línea para la vista personalizada
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy # Esto establece la asociación entre User y Article
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to articles_path, notice: 'Artículo creado exitosamente.'
    else
      render :new
    end
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments
    @comment = Comment.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to article_path(@article), notice: 'Artículo actualizado exitosamente.'
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path, notice: 'Artículo eliminado exitosamente.'
  end

  private

  def article_params
    params.require(:article).permit(:title, :banner_url,:content)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def show_article
    @article = Article.find(params[:id])
    @comments = @article.comments
    @comment = Comment.new
  end
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @article, notice: 'Comentario creado exitosamente.'
    else
      render 'articles/show'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://media.istockphoto.com/id/1270839889/fr/photo/livre-ouvert-et-ordinateur-portable-dans-la-biblioth%C3%A8que.jpg?s=1024x1024&w=is&k=20&c=3ck8MCcUefmalpQdKRyrRlw421UGW7yY0q7kZl6RQY4=);">
  <div class="container">
    <h1>Le Wagon brings <strong>tech skills</strong> to <strong>creative people</strong>!</h1>
    <p>Change your life and learn to code at one of our campuses around the world.</p>
    <a class="btn btn-flat" href="<%= new_article_path %>" class="btn btn-primary">Discover</a>
  </div>
</div>

<h1>Lista de Artículos</h1>
<div class="cards">
<% @articles.each do |article| %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))", <%= link_to article.banner_url, article %>>
  <h2><%= link_to article.title, article %></h2>
  <p><%= article.content.truncate(200) %></p>
    <p>Escrito por: <%= article.user.email %></p>

    <hr>
  <% end %>
  </div>

app/views/articles/new.html.erb
<h1>Crear un nuevo artículo</h1>

<%= form_with(model: @article, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :title, 'Título' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :content, 'Contenido' %>
    <%= form.text_area :content, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :banner_url, 'URL del banner de la imagen' %>
    <%= form.text_field :banner_url, class: 'form-control' %>
  </div>

  <%= form.submit 'Crear artículo', class: 'btn btn-primary' %>
<% end %>

app/views/articles/show.html.erb
<h2>Comentarios</h2>
<% @comments.each do |comment| %>
  <p><strong><%= comment.user.email %>:</strong> <%= comment.content %></p>
<% end %>

<% if user_signed_in? %>
  <%= form_for([@article, @comment]) do |f| %>
    <div class="field">
      <%= f.label :content %>
      <%= f.text_area :content, rows: 4 %>
    </div>
    <div class="actions">
      <%= f.submit 'Agregar comentario' %>
    </div>
  <% end %>
<% else %>
  <p>Por favor, inicia sesión para comentar.</p>
<% end %>
<%= link_to 'Volver al artículo', article_path(@article) %>
<%= link_to 'Volver al menú principal', root_path %>

app/views/comments/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.content %></p>

<h2>Comentarios</h2>
<% @comments.each do |comment| %>
  <p><strong><%= comment.user.email %>:</strong> <%= comment.content %></p>
<% end %>

<% if user_signed_in? %>
  <%= form_for([@article, @comment]) do |f| %>
    <div class="field">
      <%= f.label :content %>
      <%= f.text_area :content, rows: 4 %>
    </div>
    <div class="actions">
      <%= f.submit 'Agregar comentario' %>
    </div>
  <% end %>
<% else %>
  <p>Por favor, inicia sesión para comentar.</p>
<% end %>
<% @comments.each do |comment| %>
  <p><strong><%= comment.user.email %>:</strong> <%= comment.content %></p>
  <% if user_signed_in? %>
    <%= link_to 'Editar comentario', edit_article_comment_path(@article, comment), class: 'btn btn-primary' %>
  <% end %>
<% end %>

<%= link_to 'Volver al menú principal', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_importmap_tags %>
    <!-- Hotjar Tracking Code for my site -->
    <script>
        (function(h,o,t,j,a,r){
            h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
            h._hjSettings={hjid:3299800,hjsv:6};
            a=o.getElementsByTagName('head')[0];
            r=o.createElement('script');r.async=1;
            r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
            a.appendChild(r);
        })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
    </script>
  </head>

  <body>
      <%= render 'shared/navbar' %>
    <%= yield %>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with ❤ at Antibes
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "avatar.jpg", width: 20, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>

        <li>
          <%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link"%>
        </li>
      </ul>
    </div>
  </div>
</div>